Create Workato Connect adapter
cloudblue/connect-extension-workato pull request #1
Opened 2021-08-26 08:58 UTC by ivan-pencic-devtech

Implement triggers:
	Poll fulfillment requests
Implement actions:
	Purchase, Change quantity and Cancel request

2021-09-01 08:14 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +
delete this line

2021-09-01 08:15 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +
delete this line

2021-09-01 08:15 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +
delete this line

2021-09-01 08:17 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +  # API key authentication example. See more examples at https://docs.workato.com/developing-connectors/sdk/guides/authentication.html
delete this comment, it's from Workato sample

2021-09-01 08:17 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +      # Calendly uses header auth (Authorization: <api key>)
delete this comment, it has no relation to the connector, it's from Workato sample

2021-09-01 08:20 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +    },
these structures look very similar. suggestion is to replace them with a single structure 'created_request'

2021-09-01 08:27 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +      help: "<a href='https://connect.cloudblue.com/community/api/openapi/#operations-Assets-request_list_listRequests' target='_blank'>Official documentation</a>",
this looks like incorrect URL. Correct URL is https://connect.cloudblue.com/community/api/openapi/#operations-Assets-request_list_createRequest

2021-09-01 08:59 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +    asset_purchase_request: {
this looks like incorrect URL. Correct URL is https://connect.cloudblue.com/community/api/openapi/#operations-Assets-request_list_createRequest

2021-09-01 08:59 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +      help: "<a href='https://connect.cloudblue.com/community/api/openapi/#operations-Assets-request_list_listRequests' target='_blank'>Official documentation</a>",
this looks like incorrect URL. Correct URL is https://connect.cloudblue.com/community/api/openapi/#operations-Assets-request_list_createRequest

2021-09-01 09:00 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +            label: "Asset External UID1",
why is it UID1? why '1' in the end?

2021-09-01 09:01 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +          },
formatting is broken, please fix

2021-09-01 09:01 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +         {
formatting

2021-09-01 09:02 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +         {
indent

2021-09-01 09:03 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +
formatting, indents

2021-09-01 09:03 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +
formatting indents

2021-09-01 09:04 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +        #"id"=>"#{first_item["id"].slice(0, first_item["id"].rindex("-"))}"
why do we need it? there is "workato.uuid" function to generate UID

2021-09-01 09:04 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +      },
I think we should omit this. Connect will derive connection from product and hub/marketplace.

2021-09-01 09:05 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +   }
Marketplace ID should be optional input field, not a hardcoded field.
When empty, Connect will derive it from hub ID and tier1 / tier2 contact - there is a configuration in Connect for this.

2021-09-01 09:06 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +        post("https://api.connect.cloudblue.com/public/v1/requests", params).
it should be 
```suggestion
        post("/public/v1/requests", params).
```
workato to construct the initial part of URL using base-uri method

2021-09-01 09:07 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +        post("https://api.connect.cloudblue.com/public/v1/requests", hardcoded_params).
it should be 
```suggestion
        post("/public/v1/requests", hardcoded_params).
```
workato wil construct the rest using base_uri method

2021-09-01 09:08 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +      help: "",
For sake of consistency, this action must be "Asset change request"
Also need to add help link

2021-09-01 09:08 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +              #"quantity": input["quantity"],
delete

2021-09-01 09:09 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +        #end
delete

2021-09-01 09:12 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +  }
delete.
there already was definition of 'methods' above

2021-09-01 09:13 UTC, elikhtanskiy requested changes
comments inline

2021-09-06 07:42 UTC, elikhtanskiy requested changes

2021-09-06 07:42 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +                                end
Why is it this algorithm?

Correct algorithm seems to be
```suggestion
        customer_external_uid = if input['customer_external_uid'].blank?
                                  #if no UID in input, try to look for it by external ID (or autogenerate if not found)
                                  call(:get_tier_external_uid, connection, input['customer_external_id']) 
                                else
                                  #if UID is passed in the input explicitly, let's use it
                                  input['customer_external_uid']
                                end
```

2021-09-06 07:42 UTC, elikhtanskiy commented on cloudblue_connect.custom_adapter.rb
> +                             end
Same here

```suggestion
        tier1_external_uid = if input['tier1_external_uid'].blank?
                               call(:get_tier_external_uid, connection, input['tier1_external_uid'])
                             else
                               input['tier1_external_uid']
                             end
```

2021-09-06 11:33 UTC, ivan-pencic-devtech commented on cloudblue_connect.custom_adapter.rb
> +                                end
Yes that was a mistake, I made another commit that will fix this

2021-09-06 11:34 UTC, ivan-pencic-devtech commented on cloudblue_connect.custom_adapter.rb
> +                             end
Same mistake as above, fix is pushed

2021-09-06 12:29 UTC, merged